### ISSUE TITLE
MAYA installation error

### ISSUE THREAD

**Issue by LoveMyDream-design** [chrysly/blaya#1]
Thank you very much for your script, I wanted to test the script, but something went wrong during the installation phase, when I clicked on the script, maya prompted “ # Error: invalid syntax. Perhaps you forgot a comma? ”I'm using maya2024.1, I don't know Is it a problem with the python version? Looking forward to your reply, thanks again.
![Dingtalk_20230905180336](https://github.com/chrysly/blaya/assets/73209712/baf63bc4-d3dc-42b6-b2f8-759c4fa447b4)

**Comment by chrysly** [comment]
Hi, try deleting the script and recloning from github! The contents of the script in your screenshot look a little different from what is on the repository, which means something probably got corrupted during the download.

**Comment by LoveMyDream-design** [comment]
Thanks, it worked. I just tested it and have a few ideas. The first one is that it was imported as the reference. Can the model be imported directly? Second, the naming of the model is different from that in Blender, and a prefix is added. Can it delete the prefix and make it consistent with the inside of Blender? The third point, and the most important point, is it possible to import to blender from maya? Thank you again. If my request is unreasonable, please ignore it. I am excited because I finally found a professional blender maya bridge. I think more blender maya users will also be very happy.

**Comment by chrysly** [comment]
I can definitely try to look into these, but no guarantees (sorry)! The original use case for this tool only required a quick transfer from Blender to Maya through reference and not back.

**Comment by LoveMyDream-design** [comment]
Many thanks! Looking forward to your updates!
